09 - Using functions 03

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,26 +1,26 @@
 name: 09 - Using Functions
 
 on: 
-    push:
-    workflow_dispatch:
+  push:
+  workflow_dispatch:
 
 jobs:
-    echo:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Failing step
-            run: |
-            echo "Failure"
-            exit 1
-            - name: I will be skipped
-            if: ${{ success() }}
-            run: echo "I will print if previous steps succeed."
-            - name: I will execute
-            if: ${{ failed() }}
-            run: echo "I will print if any previous step fails."
-            - name: I will execute
-            if: ${{ !canceled() }}
-            run: echo "I will always print, except when the workflow is cancelled."
-            - name: I will execute when cancelled
-            if: ${{ canceled() }}
-            run: echo "I will print when the workflow is cancelled."
+  echo:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failing step
+        run: |
+          echo "Failure"
+          exit 1
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: ${{ failed() }}
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !canceled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: ${{ canceled() }}
+        run: echo "I will print when the workflow is cancelled."
