15 - Working with Matrices 11

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -22,9 +22,9 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
       
-      - name: Fail if experimental
-        if: ${{ matrix.tag }} == 'experimental'
-        run: exit 1
+      # - name: Fail if experimental
+      #   if: ${{ matrix.tag }} == 'experimental'
+      #   run: exit 1
 
       - name: "Perform some tests: ${{ matrix.node-version }}-${{ matrix.os }}"
         run: |
@@ -42,14 +42,20 @@ jobs:
         color: [red, green]
         shape: [circle, square]
         size: [small, large]
-        include: 
-          - opacity: 50
+        include:
           - color: red
             opacity: 75
           - shape: circle
             opacity: 100
           - color: red
             shape: triangle
+          - opacity: 50
+          - color: green
+            shape: circle
+            size: medium
+        exclude:
+          - color: green
+            shape: circle
     steps:
       - name: Dummy Step
         run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
